pool:
  vmImage: 'windows-2019'

steps:
- script: |
    npm install abaplint -g
  displayName: 'ABAPLint Install'
- script: |
    abaplint --version
    abaplint -d --abaplint.json standard --outformat json --outfile report.xml "src/**/*.*"
  displayName: 'ABAPLint Version'
- script: |
    abaplint -d --abaplint.json --outformat json --outfile report.xml "src/**/*.*"
  displayName: 'ABAPLint Run'
